### ISSUE TITLE
[1.10.2] Server Crash on startup

### ISSUE THREAD

**Issue by psychofad** [The-Fireplace/Fluidity#10]
forge-1.10.2-12.18.1.2076
Fluidity-Forge-6.0.1.3
BaseMetals_1.10.2-2.4.0.11
theoneprobe-1.10-1.1.0
mcjtylib-1.10-2.0.0

Appears to crash when making Base Metal Helmets with The One Probe.

[http://pastebin.com/LZGn5rtK](http://pastebin.com/LZGn5rtK)

**Comment by The-Fireplace** [comment]
Should be fixed in Fluidity 6.0.1.4. Comment on here again if it isn't.
