### ISSUE TITLE
Crash with newer EnderIO (I think)

### ISSUE THREAD

**Issue by brisingraerowing** [The-Fireplace/Fluidity#19]
[Crash Report](https://gist.github.com/BrisingrAerowing/0cb548fa77728404cd9c53d654895ab1)

EnderIO v1.10.2-3.0.1.125
Fluidity 6.1.1

**Comment by The-Fireplace** [comment]
Thanks, I'll get to it asap.

**Comment by brisingraerowing** [comment]
Damn. That was FAST! Thanks a billion!
