### ISSUE TITLE
Prevents crafting EnderIO coloured quite clear glass

### ISSUE THREAD

**Issue by RealGrep** [The-Fireplace/Fluidity#20]
It is impossible to craft EnderIO coloured Quite Clear Glass. Due to the ore dictionary use including normal MC glass in the recipe, you always end up with vanilla coloured glass.

This is with Fluidity-6.1.3.

**Comment by The-Fireplace** [comment]
Which mods do you have loaded?

**Comment by RealGrep** [comment]
Here's a sort of list from my fml-server-latest.txt: http://hastebin.com/cuqifomeyu.md

**Comment by The-Fireplace** [comment]
Could you post a screenshot of the recipe?
EDIT: I looked it up, and the recipe shown here, I don't interfere with.
https://ftbwiki.org/Quite_Clear_Glass

**Comment by RealGrep** [comment]
Oh yeah, not that one. Er, not where I can grab a screenshot, but basically, it's the recipe where you surround one dye of whatever colour with glass. Now, how it should work is that if you surround the dye with quite clear glass, it will give tinted quite clear glass. If you surround it with vanilla glass, it makes tinted regular minecraft:glass.

However, it ends up using an oredict definition that includes both minecraft:glass and enderio's quite clear glass to make the tinted minecraft glass, which means surrounding the dye with quite clear glass now gives tinted minecraft glass. I can look this up later, if you want, but it was using an oredict name for colorless glass, the exact oredict name for which I can't recall.

**Comment by The-Fireplace** [comment]
And it works fine if you remove Fluidity?

**Comment by The-Fireplace** [comment]
If this is still a problem, please answer my question and I will re-open the issue.
