### ISSUE TITLE
Suggestion: modern metals support

### ISSUE THREAD

**Issue by darklordwonton** [The-Fireplace/Fluidity#21]
Given that base metals is supported it seems like it would make sense to support modern metals as well.

**Comment by The-Fireplace** [comment]
What exactly do you hope to see added?

**Comment by jriwanek** [comment]
I suggest you wait till 2.5 is out before adding any support for MMe, There's gonna be some quite major API changes.

**Comment by The-Fireplace** [comment]
Alright. Does this mean Base Metals will also get some major changes?

**Comment by jriwanek** [comment]
It will, I can provide you some early builds if you like.

**Comment by jriwanek** [comment]
Also, if you're on discord, feel free to come chat: http://discord.gg/PhAcu8e

**Comment by darklordwonton** [comment]
The main thing I had in mind was SAG Mill recipes, currently the only way to have modern metals metals work in the SAG Mill is to use the Enderio SAG Mill config and add them each in manually.

**Comment by jriwanek** [comment]
That'll be in ModernMetals Natively in the next release

**Comment by The-Fireplace** [comment]
If this is still an issue, comment what you want added.
