### ISSUE TITLE
[Suggestion] [1.10.2] ExU2 Compatibility with Baubles

### ISSUE THREAD

**Issue by oitsjustjose** [The-Fireplace/Fluidity#5]
(Yes, copied from my Twitter DM) - 

I don't know if it's even possible, considering it takes a lot of Item Class restructure, but I figured I'd send the idea anyways. What about adding ExU2 compatibility to Fluidity that makes the Angel Ring a Bauble? My concern about the code behind that is two things: I think the only way for this to work is for the angel ring class to implement IBauble, and second - for the class to tick when equipped as an IBauble too, checking for sufficient GridPower. Not sure if you have ideas on different methods of implementation. I've suggested re-implementation of IBauble to RWTema on the GitHub bug-tracker, but it seems as though ExU2's development is somewhat shoved off to the side, as it hasn't been updated in months and none of the recent (and numerous) bug reports have been addressed.

**Comment by The-Fireplace** [comment]
https://minecraft.curseforge.com/projects/angel-ring-to-bauble
